### ISSUE TITLE
German umlaut mapping not correct

### ISSUE THREAD

**Issue by FSharpCSharp** [thomasgalliker/Diacritics.NET#30]
I came across this project while searching for an umlaut replacement library. Find the approach to solve the general problem. Unfortunately I found that there is something wrong with the German language.

Correct is that the character ß is replaced by ss. But this is not true for the other umlauts. Actually, Ä is replaced by Ae, Ö is Oe and Ü is Ue. The same applies to lower case letters, of course. In this library, however, the translation is only done by one letter instead of two. Therefore this is actually not correct.

| Umlaut | replacement character |
|--------|-----------------------|
| Ä      | Ae                    |
| Ü      | Ue                    |
| Ö      | Oe                    |
| ä      | ae                    |
| ü      | ue                    |
| ö      | oe                    |

https://github.com/thomasgalliker/Diacritics.NET/blob/develop/Diacritics/AccentMappings/GermanAccentsMapping.cs#L10.L12

**Comment by thomasgalliker** [comment]
You‘re absolutely right. The idea was to string-replace words like „Zürich“ to an equivalent of „zurich“ in order to include such in search results. After some years of distance, I have to confess this idea was pretty stupid. 

All in all, I should update all character mappings to comply with standards. Since this is a breaking change, I‘d like the include it in the next major release.

**Comment by thomasgalliker** [comment]
@FSharpCSharp in branch #32 I prepared a change which tackles the problem you mentioned. There will be a new DiacriticsOptions which can be passed to the ReplaceDiacritics method. DiacriticsOptions has an option "Decompose" which, when enabled, decomposes ä -> ae resp. Ä to AE (when uppercase) or Ae (when begin-of-word-uppercase).
