### ISSUE TITLE
Add .NET Standard support

### ISSUE THREAD

**Issue by coosmiin** [thomasgalliker/Diacritics.NET#9]
When installing the nuget in a .NET Core project I see warnings at compile time: "Package 'Diacritics 1.0.6' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project."

It would be nice if it could be compiled under .NET Standard.

**Comment by thomasgalliker** [comment]
Thanks for asking. You're right: This package is not yet on .Net Standard. It's a huge effort to move all my nugets to .Net Standard and since this is all done for free it is low priority work. If you don't mind the effort, you're welcome to create a pull request with the proposed change. Otherwise I gonna plan it for the next release.

**Comment by thomasgalliker** [comment]
Can ouy please check the lastest nuget pre-release (1.0.7-pre2) if it works in your solution?

**Comment by coosmiin** [comment]
It works. Thanks.

**Comment by thomasgalliker** [comment]
Stable release 1.0.7 is now ready for use.
